### ISSUE TITLE
Vedonlyöntisovellus 26.4.2019

### ISSUE THREAD

**Issue by vipy123** [Anssikka/ot-harjoitustyo#1]
Ohjelma näyttää selkeältä ja koodi on siistiä. Paketit, luokat ja metodit on jaoteltu loogisesti ja selkeästi. Metodit eivät ole liian pitkiä.
Onnistuin kirjautumisessa kun suljin välillä ohjelman nimimerkin luomisen jäkeen. Käyttöliittymä on selkeä. Ohjelman logiikka on hyvä. Ohjelmaa voisi parantaa ehkä mahdollisuus lisätä vedon tulos olemassaolevaan vetoon myös myöhemmin. Tilasto-viivakaavio on hieno lisä vedonlyönnin seuraamiseen. Tietokantayhteydet toimivat hyvin ja niiden metodit ovat hienon yksinkertaisia.

**Comment by Anssikka** [comment]
Kiitos palautteesta!
